repos:
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
<<<<<<< HEAD
=======
        exclude: scanpy/tests/
>>>>>>> 7a096bf9 (add flake8 pre-commit)
